@extends('docs.layout')

@section('content')
<h1>Report</h1>

<p>
    The <code>report</code> is the way of employes to registered the report after the pool has been serviced
</p>

<h2>Resource Representation</h2>
<h4>Report</h4>
<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>type</th>
        <th>description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>completed</td>
        <td>dateTime</td>
        <td>The date and time when the pool was serviced.</td>
      </tr>
      <tr>
        <td>on_time</td>
        <td>string</td>
        <td>Whether the report was done: <code>onTime</code>, <code>late</code> or <code>early</code>. <i><strong> This is autogenerated </strong></i></td>
      </tr>
       <tr>
        <td>latitude</td>
        <td>numeric</td>
        <td>The <code>report</code> latitude location.</td>
      </tr>
       <tr>
        <td>longitude</td>
        <td>numeric</td>
        <td>The <code>report</code> longitude location.</td>
      </tr>
       <tr>
        <td>altitude</td>
        <td>numeric</td>
        <td>The <code>report</code> altitude location.</td>
      </tr>
      <tr>
        <td>accuracy</td>
        <td>numeric</td>
        <td>The <code>report</code> accuracy location.</td>
      </tr>
      <tr>
        <td>readings</td>
        <td>array</td>
        <td>The <code>readings</code> for the <code>measurements</code> that this <code>report</code> has.</td>
      </tr>
    </tbody>
  </table>
</div>

<h2>Actions</h2>

<div class="callout callout-info" role="alert">
    <ul>
        <li>
            All endpoints are relative to <a class="link--copy">{{ url('/api/v1') }}</a>
        </li>
        <li>
            All requests must be urlencoded.
        </li>
    </ul>
</div>

<table class="table table-bordered table-striped ">
  <thead>
    <tr>
      <th>Action</th>
      <th>HTTP request</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="#list_report">List reports</a></td>
      <td><h6 style="display: inline-block;"><span class="label label-success"><strong>GET</strong></span></h6>&nbsp;&nbsp;&nbsp;&nbsp;/reports</td>
      <td>Returns a list of all <code>reports</code> in your company.</td>
    </tr>
    <tr>
      <td><a href="#create_report">Create report</a></td>
      <td><h6 style="display: inline-block;"><span class="label label-warning"><strong>POST</strong></span></h6>&nbsp;&nbsp;&nbsp;&nbsp;/reports</td>
      <td>Creates new <code>report</code>.</td>
    </tr>
    <tr>
      <td><a href="#view_report">View a report</a></td>
      <td><h6 style="display: inline-block;"><span class="label label-success"><strong>GET</strong></span></h6>&nbsp;&nbsp;&nbsp;&nbsp;/reports/{id}</td>
      <td>Returns <code>report</code> information.</td>
    </tr>
    <tr>
      <td><a href="#update_report">Update a report</a></td>
      <td><h6 style="display: inline-block;"><span class="label label-default"><strong>PATCH</strong></span></h6>&nbsp;&nbsp;&nbsp;&nbsp;/reports/{id}</td>
      <td>Updates <code>report</code> information.</td>
    </tr>
    <tr>
      <td><a href="#delete_report">Delete a report</a></td>
      <td><h6 style="display: inline-block;"><span class="label label-danger"><strong>DELETE</strong></span></h6>&nbsp;&nbsp;&nbsp;&nbsp;/reports/{id}</td>
      <td>Deletes the <code>report</code>.</td>
    </tr>
  </tbody>
</table>

<br>

<h3 id="list_report">List Reports</h3>

<p>Returns a list of the <code>reports</code> in your company</p>
<p>You can query based on various parameters</p>
<br>
<pre>
    GET  {{url ('/api/v1/reports') }}
</pre>
<br>

<h5>Optional query parameters</h5>
<table class="table table-bordered table-striped ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>limit</code></td>
      <td>integer</td>
      <td>The number of results to be displayed per page. This value must be between 1 and 25. <i>Default: 5</i></td>
    </tr>
    <tr>
      <td><code>page</code></td>
      <td>integer</td>
      <td>Page of results selected.</td>
    </tr>
    <tr>
      <td><code>date</code></td>
      <td>date</td>
      <td>Filter <code>reports</code> by date. Date format is <code>YYYY-MM-DD</code></td>
    </tr>
  </tbody>
</table>

<br>

<h3 id="create_report">Create Report</h3>

<p>Create a new <code>report</code> in your company</p>
<br>
<pre>
    POST  {{url ('/api/v1/reports') }}
</pre>
<br>

<h5>Request body</h5>
<table class="table table-bordered table-striped ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
     <tr>
        <td><code>completed</code></td>
        <td>dateTime</td>
        <td>The date and time when the pool was serviced.</td>
      </tr>
       <tr>
        <td><code>latitude</code></td>
        <td>numeric</td>
        <td>The <code>report</code> latitude location.</td>
      </tr>
       <tr>
        <td><code>longitude</code></td>
        <td>numeric</td>
        <td>The <code>report</code> longitude location.</td>
      </tr>
       <tr>
        <td><code>altitude</code></td>
        <td>numeric</td>
        <td>The <code>report</code> altitude location.</td>
      </tr>
      <tr>
        <td><code>accuracy</code></td>
        <td>numeric</td>
        <td>The <code>report</code> accuracy location.</td>
      </tr>
       <tr>
        <td><code>service</code></td>
        <td>integer</td>
        <td>The id of the <code>service</code> is been reported.</td>
      </tr>
       <tr>
        <td><code>person</code></td>
        <td>integer</td>
        <td>The <code>user-role</code> that is creating the report. <i>Only System Admin can set this. Reports created by other roles are going to be posted as themselves.</i></td>
      </tr>
      <tr>
        <td><code>photos</code></td>
        <td>array</td>
        <td>Array of file photos of the pool after been serviced.<br> Reports need a minimum of 3 photos:
            <ul>
                <li>full pool photo</li>
                <li>water quality photo<i> (close up photo of the water)</i></li>
                <li>engine room photo</li>
            </ul>
        </td>
      </tr>
      <tr>
        <td><code>readings</code></td>
        <td>array</td>
        <td>An array with 2 values:
            <ul>
                <li><code>measurement</code> : The id of the global measurment for the reading.</li>
                <li><code>value</code> : The value of the reading.</li>
            </ul>
        </td>
      </tr>
    </tbody>
</table>

<br>

<h3 id="view_report">View Report</h3>

<p>Returns <code>report</code> information.</p>
<br>
<pre>
    GET  {{url ('/api/v1/reports/{report_id}') }}
</pre>
<br>

<h3 id="update_report">Update Report</h3>

<p>Update the <code>report</code> information.</p>
<br>
<pre>
    PATCH  {{url ('/api/v1/reports/{report_id}') }}
</pre>
<br>

<h5>Request body</h5>
<table class="table table-bordered table-striped ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
    </tr>
  </thead>
   <tbody>
     <tr>
        <td><code>completed</code></td>
        <td>dateTime</td>
        <td>The date and time when the pool was serviced.</td>
      </tr>
       <tr>
        <td><code>latitude</code></td>
        <td>numeric</td>
        <td>The <code>report</code> latitude location.</td>
      </tr>
       <tr>
        <td><code>longitude</code></td>
        <td>numeric</td>
        <td>The <code>report</code> longitude location.</td>
      </tr>
       <tr>
        <td><code>altitude</code></td>
        <td>numeric</td>
        <td>The <code>report</code> altitude location.</td>
      </tr>
      <tr>
        <td><code>accuracy</code></td>
        <td>numeric</td>
        <td>The <code>report</code> accuracy location.</td>
      </tr>
       <tr>
        <td><code>person</code></td>
        <td>integer</td>
        <td>The <code>user-role</code> that is creating the report. <i>Only System Admin can change this.</i></td>
      </tr>
      <tr>
        <td><code>add_photos</code></td>
        <td>array</td>
        <td>Array of file photos of the pool after been serviced.</td>
      </tr>
       <tr>
        <td><code>remove_photos</code></td>
        <td>array</td>
        <td>Array of integers of the order of the pool photo you want to remove.</td>
      </tr>
      <tr>
        <td><code>add_readings</code></td>
        <td>array</td>
        <td>An array with 2 values:
            <ul>
                <li><code>measurement</code> : The id of the global measurment for the reading.</li>
                <li><code>value</code> : The value of the reading.</li>
            </ul>
        </td>
      </tr>
    </tbody>
</table>

<br>

<h3 id="delete_report">Delete Report</h3>

<p>Delete the <code>report</code>.</p>
<br>
<pre>
    DELETE  {{url ('/api/v1/reports/{report_id}') }}
</pre>

@endsection
